name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test1:
    name: Test 1
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1
        run: echo Hello 1

      - name: Step 2
        run: echo Hello 2

      - name: Step 2.5
        run: echo Hello 2.5

      - name: Step 3
        if: false
        run: echo Hello 3

      - name: Step 4
        continue-on-error: true
        run: exit 1

      - name: Step 5
        if: always()
        run: echo Hello 5
  
  test3:
    name: Test 2
    runs-on: ubuntu-latest
    if: false
    steps:
      - uses: actions/checkout@v2

  test2:
    name: Test 2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Step 1
        run: echo Hello 1

      - name: Step 2
        run: echo Hello 2
  
  run-action:
    name: Run action
    runs-on: ubuntu-latest
    needs: ['test1', 'test2', 'test3']
    if: always()

    steps:
      - uses: actions/checkout@v2
      
      - name: Run this action
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
